SELECT GROUPS.GROUP_TYPE AS Статья, PAYMENT.PAYMENT_DATE AS Дата, PAYMENT.FOR_MONTH AS [За месяц], (PERSON.LASTNAME &' '& PERSON.FIRSTNAME) AS Инструктор, GROUPS.FULLNAME AS [Группа/Основание], (PERSON_1.LASTNAME  &' '& PERSON_1.FIRSTNAME) AS Клиент, PAYMENT.SUMMA AS Сумма
FROM (PERSON INNER JOIN (TRAINER INNER JOIN (GROUPS INNER JOIN PAYMENT ON GROUPS.GROUP_ID = PAYMENT.GROUP_ID) ON TRAINER.TRAINER_ID = PAYMENT.TRAINER_ID) ON PERSON.PERSON_ID = TRAINER.PERSON_ID) 
INNER JOIN PERSON AS PERSON_1 ON PAYMENT.PERSON_ID = PERSON_1.PERSON_ID
WHERE (PAYMENT.CLAUSE = 1)
UNION ALL
SELECT PAYMENT.CLAUSE, PAYMENT.PAYMENT_DATE, Null, Null, PAYMENT.REASON, (PERSON.LASTNAME &' '& PERSON.FIRSTNAME), PAYMENT.SUMMA
FROM PAYMENT 
INNER JOIN PERSON ON PERSON.PERSON_ID = PAYMENT.PERSON_ID
WHERE (PAYMENT.CLAUSE = 9)
UNION ALL
SELECT PAYMENT.CLAUSE, PAYMENT.PAYMENT_DATE, Null, Null, PAYMENT.REASON, ORGANIZATION.FULLNAME, PAYMENT.SUMMA
FROM PAYMENT 
INNER JOIN ORGANIZATION ON ORGANIZATION.ORGANIZATION_ID = PAYMENT.ORGANIZATION_ID
WHERE (PAYMENT.CLAUSE = 10)

