SELECT PAYMENT.CLAUSE AS Статья, PAYMENT.PAYMENT_DATE AS Дата, PAYMENT.FOR_MONTH AS [За месяц], 'Заработная плата' AS Основание, (PERSON.LASTNAME  &' '& PERSON.FIRSTNAME) AS Клиент, PAYMENT.SUMMA AS Сумма
FROM PAYMENT
INNER JOIN PERSON ON PERSON.PERSON_ID = PAYMENT.PERSON_ID
WHERE (PAYMENT.CLAUSE IN (2, 3))
UNION ALL
SELECT PAYMENT.CLAUSE, PAYMENT.PAYMENT_DATE, PAYMENT.FOR_MONTH, PAYMENT.REASON, ORGANIZATION.FULLNAME, PAYMENT.SUMMA
FROM PAYMENT 
INNER JOIN ORGANIZATION ON ORGANIZATION.ORGANIZATION_ID = PAYMENT.ORGANIZATION_ID
WHERE (PAYMENT.DIRECTION = False)


