SELECT IIf(GROUPS.GROUP_TYPE = 1, 'Взрослые группы', IIf(GROUPS.GROUP_TYPE = 2, 'Детские группы', 'Индивидуальные')) AS Статья, 
	PAYMENT.PAYMENT_DATE AS Дата, 
	PAYMENT.FOR_MONTH AS [За месяц], 
	(PERSON.LASTNAME &' '& PERSON.FIRSTNAME) AS [Инструктор/Статья], 
	GROUPS.FULLNAME AS [Группа/Основание], 
	(PERSON_1.LASTNAME  &' '& PERSON_1.FIRSTNAME) AS Клиент, 
	PAYMENT.SUMMA AS Сумма
FROM (PERSON INNER JOIN (TRAINER INNER JOIN (GROUPS INNER JOIN PAYMENT ON GROUPS.GROUP_ID = PAYMENT.GROUP_ID) ON TRAINER.TRAINER_ID = PAYMENT.TRAINER_ID) ON PERSON.PERSON_ID = TRAINER.PERSON_ID) 
INNER JOIN PERSON AS PERSON_1 ON PAYMENT.PERSON_ID = PERSON_1.PERSON_ID
WHERE (PAYMENT.CLAUSE = 1)
UNION ALL
SELECT IIf(PAYMENT.CLAUSE = 2, 'ЗП инструторам', IIf(PAYMENT.CLAUSE = 3, 'ЗП работникам', 'Продажа товаров и услуг')), 
	PAYMENT.PAYMENT_DATE, 
	IIf(PAYMENT.FOR_MONTH is Null, '', PAYMENT.FOR_MONTH), 
	IIf(PAYMENT.CLAUSE = 9, 'Продажа товаров и услуг', ''), 
	IIf(PAYMENT.CLAUSE IN (2, 3), 'Заработная плата', PAYMENT.REASON), 
	(PERSON.LASTNAME &' '& PERSON.FIRSTNAME), 
	PAYMENT.SUMMA
FROM PAYMENT 
INNER JOIN PERSON ON PERSON.PERSON_ID = PAYMENT.PERSON_ID
WHERE (PAYMENT.CLAUSE IN (9, 2, 3))
UNION ALL
SELECT IIf(PAYMENT.CLAUSE = 4, 'Административные расходы', IIf(PAYMENT.CLAUSE = 5, 'Аренда', IIf(PAYMENT.CLAUSE = 8, 'Интерьер', IIf(PAYMENT.CLAUSE = 10, 'Прочие доходы', IIf(PAYMENT.CLAUSE = 11, 'Прочие расходы', IIf(PAYMENT.CLAUSE = 12, 'Реклама', IIf(PAYMENT.CLAUSE = 13, 'Спортивный инвентарь', 'Хозяйственные расходы'))))))), 
	PAYMENT.PAYMENT_DATE, 
	IIf(PAYMENT.FOR_MONTH is Null, '', PAYMENT.FOR_MONTH), IIf(PAYMENT.CLAUSE = 10, 'Прочие доходы', ''), 
	IIf(PAYMENT.CLAUSE = 5, 'Аренда', PAYMENT.REASON), 
	ORGANIZATION.FULLNAME, 
	PAYMENT.SUMMA
FROM PAYMENT 
INNER JOIN ORGANIZATION ON ORGANIZATION.ORGANIZATION_ID = PAYMENT.ORGANIZATION_ID
WHERE (PAYMENT.CLAUSE IN (10, 4, 5, 8, 11, 12, 13, 14))