
SELECT ID, IS_DELETED, IS_REPLICATED, EXPENSE_TYPE_ID, RECORD_TYPE, EXPENSE_DATE, NAME, PAYMENT_TYPE, SHOP_ID, COST, COMMENT,
DATEADD(SECOND, EXPENSE_DATE, cast('1970-01-01 00:00:00' as timestamp))
FROM EXPENSES
where IS_DELETED=0
order by DATEADD(SECOND, EXPENSE_DATE, cast('1970-01-01 00:00:00' as timestamp)) desc