--ALTER TABLE EXPENSES ADD blobcolumn_new BLOB SUB_TYPE TEXT CHARACTER SET WIN1251;
--UPDATE EXPENSES SET blobcolumn_new = COMMENT;
--ALTER TABLE EXPENSES DROP COMMENT;
--ALTER TABLE EXPENSES ALTER COLUMN blobcolumn_new TO COMMENT;
--
--ALTER TABLE WAYBILLS ADD blobcolumn_new BLOB SUB_TYPE TEXT CHARACTER SET WIN1251;
--UPDATE WAYBILLS SET blobcolumn_new = COMMENT;
--ALTER TABLE WAYBILLS DROP COMMENT;
--ALTER TABLE WAYBILLS ALTER COLUMN blobcolumn_new TO COMMENT;
--
--ALTER TABLE SUPPLIERS ADD blobcolumn_new BLOB SUB_TYPE TEXT CHARACTER SET WIN1251;
--UPDATE SUPPLIERS SET blobcolumn_new = COMMENT;
--ALTER TABLE SUPPLIERS DROP COMMENT;
--ALTER TABLE SUPPLIERS ALTER COLUMN blobcolumn_new TO COMMENT;
--
ALTER TABLE OPERATIONS ADD blobcolumn_new BLOB SUB_TYPE TEXT CHARACTER SET WIN1251;
--UPDATE OPERATIONS SET blobcolumn_new = OPERATION_DESCRIPTION;
--ALTER TABLE OPERATIONS DROP OPERATION_DESCRIPTION;
--ALTER TABLE OPERATIONS ALTER COLUMN blobcolumn_new TO OPERATION_DESCRIPTION;


