--Прочие доходы и прочие расходы
SELECT E.RECORD_TYPE AS "Направление", 
	IIf(E.EXPENSE_TYPE_ID = 2, 'Доставка', NULL) AS "Группа товара",
	IIF(ET.NAME IS NOT NULL, ET.NAME, 'Статья не указана') AS "Статья",
	CASE WHEN E.EXPENSE_TYPE_ID IN (2) THEN NULL
		WHEN E.EXPENSE_TYPE_ID IN (5,6,7,10) THEN 'Переменные'
		WHEN E.EXPENSE_TYPE_ID IN (11,13) THEN 'Постоянные'
		WHEN E.EXPENSE_TYPE_ID IN (3,8,14) THEN 'Инвестиции'
		ELSE 'Тип расходов не указан'
		END	AS "Тип расходов",
	NULL AS "Заказчик",
	NULL AS "Наименование",
	NULL AS "Размер",
	NULL AS "Кол.",
	NULL AS "Скидка, %",
	E.COMMENT AS "Основание", 
	NULL AS "Поставщик",
	DATEADD(SECOND, E.EXPENSE_DATE, cast('1970-01-01 00:00:00' as timestamp)) AS "Дата", 
	COST AS "Сумма",
	COST AS "Сумма оплат",
	NULL AS "Сумма задолженностей",
	0 AS DEBT,
	0 AS RESERVE
FROM EXPENSES E
	LEFT JOIN EXPENSE_TYPES ET ON (ET.ID = E.EXPENSE_TYPE_ID)
	WHERE EXPENSE_TYPE_ID NOT IN (-3,-2,9,4,12,15) AND E.IS_DELETED=0
UNION ALL
--Доходы от продажи товаров и расходы на их закупку (выданные заказы только без задолженностей и резервированные товары только без предоплаты)
SELECT (-1)*RECORD_TYPE,
	IIF(GG.NAME IS NOT NULL, GG.NAME, 'Др. товары'),
	IIF(GG.NAME IS NOT NULL, GG.NAME, 'Др. товары'),
	IIf(RECORD_TYPE=1,'Переменные', NULL),
	SUP.NAME,
	G.NAME,
	S.NAME,
	WI.QUANTITY,
	IIf(WI.PRICE>0, WI.DISCOUNT/WI.PRICE*100, 0),
	G.NAME,
	SUP.NAME,
	DATEADD(SECOND, W.WAYBILL_DATE, cast('1970-01-01 00:00:00' as timestamp)), --IIF(W.RESERVE_UNTIL=0,DATEADD(SECOND, W.WAYBILL_DATE, cast('1970-01-01 00:00:00' as timestamp)),DATEADD(SECOND, W.RESERVE_UNTIL, cast('1970-01-01 00:00:00' as timestamp))),
	IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT)*(W.PAID/W.COST), 0),
	IIf((RECORD_TYPE=-1) AND (W.IS_RESERVE = 0), WI.QUANTITY*(WI.PRICE-WI.DISCOUNT), NULL),
	IIf((RECORD_TYPE=-1) AND (W.IS_RESERVE = 1), WI.QUANTITY*(WI.PRICE-WI.DISCOUNT), NULL),
	0,
	W.IS_RESERVE
FROM
	WAYBILL_ITEMS WI
	JOIN WAYBILLS W ON (W.ID = WI.WAYBILL_ID)
	LEFT JOIN SUPPLIERS SUP ON (SUP.ID = W.CONTRACTOR_ID)
	JOIN GOODS G ON (WI.GOODS_ID = G.ID)
	LEFT JOIN SIZES S ON (WI.SIZE_ID = S.ID)
	LEFT JOIN GOOD_GROUPS GG ON (GG.ID = G.GROUP_ID)
	WHERE W.IS_DELETED = 0 AND WI.IS_DELETED = 0 AND W.RECORD_TYPE IN (-1,1) AND ((W.COST = 0) OR (W.PAID > 0))
UNION ALL
--Выданные заказы с задолженностями
SELECT (-1)*RECORD_TYPE,
	IIF(GG.NAME IS NOT NULL, GG.NAME, 'Др. товары'),
	IIF(GG.NAME IS NOT NULL, GG.NAME, 'Др. товары'),
	IIf(RECORD_TYPE=1,'Переменные', NULL),
	SUP.NAME,
	G.NAME,
	S.NAME,
	WI.QUANTITY,
	IIf(WI.PRICE>0, WI.DISCOUNT/WI.PRICE*100, 0),
	G.NAME,
	SUP.NAME,
	DATEADD(SECOND, W.WAYBILL_DATE, cast('1970-01-01 00:00:00' as timestamp)), --IIF(W.RESERVE_UNTIL=0,DATEADD(SECOND, W.WAYBILL_DATE, cast('1970-01-01 00:00:00' as timestamp)),DATEADD(SECOND, W.RESERVE_UNTIL, cast('1970-01-01 00:00:00' as timestamp))),
	WI.QUANTITY*(WI.PRICE-WI.DISCOUNT)*(1-W.PAID/W.COST),
	IIf((RECORD_TYPE=-1) AND (W.IS_RESERVE = 0), WI.QUANTITY*(WI.PRICE-WI.DISCOUNT), NULL),
	IIf((RECORD_TYPE=-1) AND (W.IS_RESERVE = 1), WI.QUANTITY*(WI.PRICE-WI.DISCOUNT), NULL),
	1,
	W.IS_RESERVE
FROM
	WAYBILL_ITEMS WI
	JOIN WAYBILLS W ON (W.ID = WI.WAYBILL_ID)
	LEFT JOIN SUPPLIERS SUP ON (SUP.ID = W.CONTRACTOR_ID)
	JOIN GOODS G ON (WI.GOODS_ID = G.ID)
	LEFT JOIN SIZES S ON (WI.SIZE_ID = S.ID)
	LEFT JOIN GOOD_GROUPS GG ON (GG.ID = G.GROUP_ID)
	WHERE W.IS_DELETED = 0 AND WI.IS_DELETED = 0 AND W.RECORD_TYPE IN (-1,1) AND (W.PAID < W.COST)