select calendar_date,
	iif(extract(weekday from calendar_date) in (6,0), 1, 0) as WEEKEND,
	iif(extract(weekday from calendar_date) in (6,0), 1000000, 0) as WEEKEND_1000000,
	50000*12/365 as CONSTANT_EXPENSES,
	85000*12/365 as CONSTANT_EXPENSES_WITH_ALENA,
	T1.*
from CALENDAR
	left join
	( 
	--Даты заказов и неосуществленная прибыль от неоплаченных частей
	SELECT W.ID AS WB_ID,
		SUP.NAME AS CLIENT,
		G.ID AS GOOD_ID,
		G.NAME AS GOOD_NAME,
		S.NAME AS SIZE_NAME,
		WI.QUANTITY AS QUANTITY,
		DATEADD(SECOND, W.WAYBILL_DATE, cast('1970-01-01 00:00:00' as timestamp)) AS JDATE,
		DATEADD(SECOND, W.WAYBILL_DATE, cast('1970-01-01 00:00:00' as timestamp)) AS WDATE, --IIF(W.RESERVE_UNTIL=0,DATEADD(SECOND, W.WAYBILL_DATE, cast('1970-01-01 00:00:00' as timestamp)),DATEADD(SECOND, W.RESERVE_UNTIL, cast('1970-01-01 00:00:00' as timestamp))),
		NULL AS PDATE,
		IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT)*(W.PAID/W.COST), 0) AS PAID,
		IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT)*(1 - W.PAID/W.COST), 0) AS DEBT,
		IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT-NC.COST_BROOK)*(1 - W.PAID/W.COST), 0) AS RESERVE_BROOK,
		IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT-NC.COST_DMITROV)*(1 - W.PAID/W.COST), 0) AS RESERVE_DMITROV,
		0 AS PROFIT_BROOK,
		0 AS PROFIT_DMITROV,
		W.IS_RESERVE AS RESERVED,
		S.IS_DELETED AS SIZE_DELETED
	FROM
		WAYBILL_ITEMS WI
		JOIN WAYBILLS W ON (W.ID = WI.WAYBILL_ID)
		LEFT JOIN SUPPLIERS SUP ON (SUP.ID = W.CONTRACTOR_ID)
		JOIN GOODS G ON (WI.GOODS_ID = G.ID)
		LEFT JOIN SIZES S ON (WI.SIZE_ID = S.ID)
		LEFT JOIN SIZED_REMAINDERS SR ON (WI.SIZE_ID = SR.SIZE_ID)
		LEFT JOIN GOOD_GROUPS GG ON (GG.ID = G.GROUP_ID)
		JOIN NET_COST NC ON (NC.GOOD_ID = G.ID)
		WHERE W.IS_DELETED = 0 AND WI.IS_DELETED = 0 AND SR.SHOP_ID=0 and W.RECORD_TYPE = -1 AND IIF(W.COST>0, (1 - W.PAID/W.COST), 0)>0
	UNION ALL
	--Даты платежей и прибыль
	SELECT W.ID AS WAYBILL_ID,
		SUP.NAME AS CLIENT,
		G.ID AS GOOD_ID,
		G.NAME AS GOOD_NAME,
		S.NAME AS SIZE_NAME,
		WI.QUANTITY AS QUANTITY,
		DATEADD(SECOND, P.PAYMENT_DATE, cast('1970-01-01 00:00:00' as timestamp)) AS PDATE,
		NULL,
		DATEADD(SECOND, P.PAYMENT_DATE, cast('1970-01-01 00:00:00' as timestamp)) AS PDATE,
		IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT)*(W.PAID/W.COST), 0) AS PAID,
		IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT)*(1 - W.PAID/W.COST), 0) AS DEBT,
		0,
		0,
		IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT-NC.COST_BROOK)*(P.COST/W.COST), 0) AS PROFIT_BROOK,
		IIF(W.COST>0, WI.QUANTITY*(WI.PRICE-WI.DISCOUNT-NC.COST_DMITROV)*(P.COST/W.COST), 0) AS PROFIT_DMITROV,
		W.IS_RESERVE AS RESERVED,
		S.IS_DELETED AS SIZE_DELETED
	FROM
		WAYBILL_ITEMS WI
		JOIN WAYBILLS W ON (W.ID = WI.WAYBILL_ID)
		LEFT JOIN PAYMENTS P ON (W.ID = P.WAYBILL_ID)
		LEFT JOIN SUPPLIERS SUP ON (SUP.ID = W.CONTRACTOR_ID)
		JOIN GOODS G ON (WI.GOODS_ID = G.ID)
		LEFT JOIN SIZES S ON (WI.SIZE_ID = S.ID)
		LEFT JOIN SIZED_REMAINDERS SR ON (WI.SIZE_ID = SR.SIZE_ID)
		LEFT JOIN GOOD_GROUPS GG ON (GG.ID = G.GROUP_ID)
		JOIN NET_COST NC ON (NC.GOOD_ID = G.ID)
		WHERE W.IS_DELETED = 0 AND WI.IS_DELETED = 0 AND P.IS_DELETED = 0 AND SR.SHOP_ID=0 and W.RECORD_TYPE = -1 AND W.PAID>0
	) as T1
	ON CAST(T1.JDATE AS DATE) = CALENDAR.CALENDAR_DATE