WITH DIV_M AS (
SELECT E_DATE AS E_MONTH,
	SUM(SUMMA) AS DIV_MONTH,
	IIF(SUM(SUMMA)>0, 0.3*SUM(SUMMA), 0) AS DIV_MONTH_RV,
	IIF(SUM(SUMMA)>0, 0.2*SUM(SUMMA), 0) AS DIV_MONTH_IA,
	SUM(INV_SUMMA) AS INV_MONTH
FROM    (
		--EXPENSES (WITHOUT INVESTMENTS)
		SELECT CAST(LEFT(DATEADD(SECOND, E.EXPENSE_DATE, cast('1970-01-01 00:00:00' as timestamp)), 8)||'01' AS DATE) AS E_DATE,
			COST*RECORD_TYPE AS SUMMA,
			0 AS INV_SUMMA
		FROM EXPENSES E
			WHERE EXPENSE_TYPE_ID NOT IN (-3,-2,9,4,12,15) AND EXPENSE_TYPE_ID NOT IN (3,8,14) AND IS_DELETED = 0
		UNION ALL
		--INVESTMENTS
		SELECT CAST(LEFT(DATEADD(SECOND, E.EXPENSE_DATE, cast('1970-01-01 00:00:00' as timestamp)), 8)||'01' AS DATE),
			0,
			COST*RECORD_TYPE
		FROM EXPENSES E
			WHERE EXPENSE_TYPE_ID IN (3,8,14) AND IS_DELETED = 0
		UNION ALL
		--WAYBILLS
		SELECT CAST(LEFT(DATEADD(SECOND, W.WAYBILL_DATE, cast('1970-01-01 00:00:00' as timestamp)), 8)||'01' AS DATE),
			(-1)*W.RECORD_TYPE*W.PAID,
			0
		FROM WAYBILLS W
			WHERE W.IS_DELETED = 0 AND W.RECORD_TYPE IN (-1,1)
		) AS PAYMENTS
	GROUP BY E_DATE
),
DIV_T AS (
SELECT SUM(IIF(EXPENSE_TYPE_ID = 15, COST, 0)) AS DIV_TOTAL_RV, 
	SUM(IIF(EXPENSE_TYPE_ID = 12, COST, 0)) AS DIV_TOTAL_IA
FROM EXPENSES
	WHERE EXPENSE_TYPE_ID IN (12,15) AND IS_DELETED = 0
),
DIV_T_PLAN AS (
SELECT SUM(DIV_MONTH_RV) AS DIV_T_PLAN_RV, 
	SUM(DIV_MONTH_IA) AS DIV_T_PLAN_IA
FROM DIV_M
),
DIV_I AS (
SELECT DIV_M.E_MONTH, SUM(DM1.DIV_MONTH_RV) AS DIV_INT_RV, SUM(DM1.DIV_MONTH_IA) AS DIV_INT_IA
FROM DIV_M
	JOIN DIV_M AS DM1 ON (DIV_M.E_MONTH >= DM1.E_MONTH),
	DIV_T
	GROUP BY DIV_M.E_MONTH
),
DIV_F AS (
SELECT DIV_M.E_MONTH,
	IIF(DIV_TOTAL_RV>=DIV_INT_RV, DIV_MONTH_RV, IIF(DIV_INT_RV-DIV_TOTAL_RV>=DIV_MONTH_RV, 0, DIV_MONTH_RV-DIV_INT_RV+DIV_TOTAL_RV)) AS DIV_FACT_RV,
	IIF(DIV_TOTAL_IA>=DIV_INT_IA, DIV_MONTH_IA, IIF(DIV_INT_IA-DIV_TOTAL_IA>=DIV_MONTH_IA, 0, DIV_MONTH_IA-DIV_INT_IA+DIV_TOTAL_IA)) AS DIV_FACT_IA
FROM DIV_I JOIN DIV_M USING (E_MONTH), DIV_T
)
SELECT DIV_M.E_MONTH, 
	DIV_MONTH-DIV_FACT_RV-DIV_FACT_IA AS DIV_FACT_BANK, 
	DIV_FACT_RV, 
	DIV_FACT_IA, 
	INV_MONTH, 
	DIV_MONTH-DIV_FACT_RV-DIV_FACT_IA+INV_MONTH AS DIV_INV_BALANCE,
	DIV_T_PLAN.DIV_T_PLAN_RV-DIV_T.DIV_TOTAL_RV AS DIV_RV_BALANCE,
	DIV_T_PLAN.DIV_T_PLAN_IA-DIV_T.DIV_TOTAL_IA AS DIV_IA_BALANCE
FROM DIV_F 
	JOIN DIV_M USING (E_MONTH),
	 DIV_T, DIV_T_PLAN
	--JOIN DIV_T USING (E_MONTH)