SELECT ATTENDANCE.TRAINING_ID, CLIENT.CLIENT_ID, CLIENT_TOTAL_DEBT.DEBT, T1.[Count-CAME], T1.GROUP_ID, T1.FOR_MONTH
FROM PERSON
  INNER JOIN ((
    (CLIENT LEFT JOIN CLIENT_TOTAL_DEBT ON CLIENT.CLIENT_ID = CLIENT_TOTAL_DEBT.CLIENT_ID)
    LEFT JOIN (SELECT * FROM CLIENT_MONTH_GROUP_ATTENDANCE WHERE GROUP_ID=Forms!Группы!GROUP_ID And FOR_YEAR=Year(Forms!Группы!TRAINING_SUB!CREATE_DATE) And FOR_MONTH=Month(Forms!Группы!TRAINING_SUB!CREATE_DATE))  AS T1
      ON CLIENT.CLIENT_ID = T1.CLIENT_ID)
    INNER JOIN ATTENDANCE ON CLIENT.CLIENT_ID = ATTENDANCE.CLIENT_ID)
  ON PERSON.PERSON_ID = CLIENT.PERSON_ID
ORDER BY PERSON.LASTNAME;
